/* eslint-disable */
// Generated by component library do not modify
import ComponentsButtonButton from './components/Button/Button.js';

function dispatchEvent(data) {
  if (typeof window !== 'undefined') {
    const BluekitEvent = require('react-bluekit/lib/libraries/BluekitEvent');
    document.dispatchEvent(BluekitEvent.default('functionTriggered', data));
  } else
    console.log('Bluekit received function triggered', data)
}

export default {
  ComponentsButtonButton: {
    name: 'ComponentsButtonButton',
    menu: 'Components Button Button',
    file: './components/Button/Button.js',
    component: ComponentsButtonButton,
    componentName: 'Button',
    description: '',
    customProps: {},
    propsDefinition: {children:{type:{name:"node"},required:true,description:""},className:{type:{name:"string"},required:false,description:"",defaultValue:{value:"null",computed:false}},disabled:{type:{name:"bool"},required:false,description:"",defaultValue:{value:"false",computed:false}},isLoading:{type:{name:"bool"},required:false,description:"",defaultValue:{value:"false",computed:false}},onClick:{type:{name:"func"},required:false,description:"",defaultValue:{value:"null",computed:false}},type:{type:{name:"enum",value:[{value:"'primary'",computed:false},{value:"'secondary'",computed:false},{value:"'success'",computed:false},{value:"'danger'",computed:false},{value:"'dark'",computed:false}]},required:false,description:"",defaultValue:{value:"'primary'",computed:false}}},
    simpleProps: {children:"NODE children",className:null,disabled:false,isLoading:false,onClick:null,type:"primary"},
    fullProps: {children:"NODE children",className:null,disabled:false,isLoading:false,onClick:null,type:"primary"}
  },
}
